# Book settings
title                       : Mathematik   # The title of the book. Will be placed in the left navbar.
author                      : Frederic Baumeister  # The author of the book
copyright                   : "2023"  # Copyright year to be placed in the footer
logo                        : _static/my_logo.png
execute:
  execute_notebooks: "auto"
